version: '3'

services:
  db:
    image: mariadb:10.11
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3308:3306"
    environment:
      - 'MYSQL_USER=root'
      - 'MYSQL_ROOT_PASSWORD=123456'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
