name: Before Merge

on:
  push:
    branches-ignore:
      - master

# TODO split jobs into build and test
jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    strategy:
      matrix:
        # TODO add firefox and edige
        browser: [ chrome ]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Read .node-version
        id: node-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.node-version

      - name: Use Node.js ${{ steps.node-version.outputs.content }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.content }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup environment variables
        run: npm run setup

      - name: Build
        run: npm run build

      - name: Unit Tests
        run: npm test

      - name: Integration Tests
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          command: npm run test:integration

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-${{ matrix.browser }}
          path: |
            cypress/videos
            cypress/screenshots
